# Generated by Django 4.1.5 on 2023-01-06 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Subscriptions', 'Subscriptions'), ('Other', 'Other')], default='Food', max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Necessities', 'Necessities'), ('Entertainment', 'Entertainment'), ('Subscriptions', 'Subscriptions'), ('Other', 'Other')], default='Food', max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
